### ISSUE TITLE
Прямо всегда int?

### ISSUE THREAD

**Issue by coursar** [dilyarakhabibullina/homeWorkLessonOneWallpaper#2]
https://github.com/dilyarakhabibullina/homeWorkLessonOneWallpaper/blob/0cf0500f603bc827c42a898f8ee0669b5c90a5d6/src/Main.java#L3-L5

**Comment by dilyarakhabibullina** [comment]
чтобы не связываться с приведением типов, сделала все измерения в см. Только мне кажется, что правильнее 1 рулон еще в конце прибавлять, так как остаток отбрасывается при расчете. Опять таки, лучше пусть побольше купят. Но поскольку в примере расчета этого не было, я не стала делать

**Comment by coursar** [comment]
Если сделали Issue - закрывайте
